sistema/musica/urls.py
from django.urls import path
from musica.views import ListarMusicas, FotoMusica, AdicionarMusicas, DeletarMusicas, EditarMusicas
from musica.views import APIListarMusicas, APIDeletarMusicas, APIAdicionarMusica, APIEditarMusica
urlpatterns = [
    path('', ListarMusicas.as_view(), name='listar-musicas'),
    path('fotos/<str:arquivo>/', FotoMusica.as_view(), name='foto-musica'),
    path('novo/', AdicionarMusicas.as_view(), name='add-musicas'),
    path('deletar/<int:pk>/', DeletarMusicas.as_view(), name='deletar-musicas'),
    path('<int:pk>/', EditarMusicas.as_view(), name='editar-musicas'),
    path('api/', APIListarMusicas.as_view(), name='api-listar-musicas'),
    path('api/<int:pk>/', APIDeletarMusicas.as_view(), name='api-deletar-musicas'),
    path('api/adicionar/', APIAdicionarMusica.as_view(), name='api-adicionar-musica'),
    path('api/editar/<int:pk>/', APIEditarMusica.as_view(), name='api-editar-musica'),
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from sistema.views import Login, Logout, LoginAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('musica/', include('musica.urls'), name='musica'),
    path('colecao/', include('colecao.urls'), name='colecao'),
    path('autenticacao-api/', LoginAPI.as_view()),
]

sistema/musica/models.py
from django.db import models
from musica.consts import *


# Create your models here.
class Musica(models.Model):
    banda = models.CharField(max_length=100)
    musica = models.CharField(max_length=100)
    ano = models.IntegerField()
    foto = models.ImageField(blank=True, null=True, upload_to='musica/fotos')
    estilo = models.SmallIntegerField(choices=OPCOES_ESTILO)

    def __str__(self):
        return '{0} - {1}'.format(

            self.banda,
            self.musica,
            self.ano,
            self.get_estilo_display()
        )
    
  
    

sistema/musica/forms.py
from django.forms import ModelForm
from musica.models import Musica


class FormularioMusica(ModelForm):

    class Meta:
        model = Musica
        exclude = []

sistema/musica/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, View, CreateView, DeleteView, UpdateView
from musica.models import Musica
from django.http import FileResponse, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from musica.forms import FormularioMusica



from musica.serializers import SerializadorMusica, SerializadorAddMusica, SerializadorEditarMusica
from rest_framework.generics import ListAPIView, DestroyAPIView, CreateAPIView, UpdateAPIView
from rest_framework import permissions
from rest_framework.authentication import TokenAuthentication




class ListarMusicas(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """
    View para listar Musicas cadastradas.
    """
    
    model = Musica
    context_object_name = 'musicas'
    template_name = 'musica/listar.html'

    def test_func(self):
        # Verifica se o usuário é um superusuário
        return self.request.user.is_superuser
    

class AdicionarMusicas(LoginRequiredMixin, CreateView, UserPassesTestMixin):
    model = Musica
    form_class = FormularioMusica
    template_name = 'musica/novo.html'
    success_url = reverse_lazy('listar-musicas')

    def test_func(self):
        # Verifica se o usuário é um superusuário
        return self.request.user.is_superuser
    


class DeletarMusicas(LoginRequiredMixin, DeleteView, UserPassesTestMixin):
    model = Musica
    template_name = 'musica/deletar.html'
    success_url = reverse_lazy('listar-musicas')

    def test_func(self):
        # Verifica se o usuário é um superusuário
        return self.request.user.is_superuser


class EditarMusicas(LoginRequiredMixin, UpdateView, UserPassesTestMixin):
    model = Musica
    form_class = FormularioMusica
    template_name = 'musica/editar.html'
    success_url = reverse_lazy('listar-musicas')

    def test_func(self):
        # Verifica se o usuário é um superusuário
        return self.request.user.is_superuser    


class FotoMusica(LoginRequiredMixin, View):
    def get(self, request, arquivo):
        try:
            musica = Musica.objects.get(foto='musica/fotos/{}'.format(arquivo))
            return FileResponse(musica.foto)
        except ObjectDoesNotExist:
            raise Http404("Foto não encontrada ou acesso não autorizado")
        except Exception as exception:
            raise exception
        


class APIListarMusicas(ListAPIView):
    '''
    View para listar instâncias de músicas (por meio do API REST)
    '''
    serializer_class = SerializadorMusica
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Musica.objects.all()


class APIDeletarMusicas(DestroyAPIView):
    """
    View para deletar instâncias de músicas (por meio da API REST)
    """
    serializer_class = SerializadorMusica
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Musica.objects.all()
    

class APIAdicionarMusica(CreateAPIView):
    """
    API para adicionar músicas.
    """
    serializer_class = SerializadorAddMusica
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save()


class APIEditarMusica(UpdateAPIView):
    """
    API para editar músicas.
    """
    serializer_class = SerializadorEditarMusica
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]
    queryset = Musica.objects.all()

sistema/templates/musica/deletar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-mus.html' %}
{% endblock %}

{% block title %}Editar Música{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Deletar Música</h2>
    <form action="{% url 'deletar-musicas' musica.pk%}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        <center>
            <div class="alert alert-danger" role="alert">
                <p>Tem certeza que deseja excluir a musica "{{object}}"?</p>
            </div>

            <input type="submit" value="Confirmar" class="btn btn-primary" />
            <a href="{% url 'listar-musicas' %}" class="btn btn-danger">Cancelar</a>
        </center>
        
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

sistema/templates/musica/editar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-mus.html' %}
{% endblock %}

{% block title %}Editar Música{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Editar Música</h2>
    <form action="{% url 'editar-musicas' musica.pk%}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_banda" class="form-label">Banda</label>
                {{ form.banda }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_musica" class="form-label">Música</label>
                {{ form.musica }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_ano" class="form-label">Ano</label>
                {{ form.ano }}
            </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_foto" class="form-label">Foto</label>
                {{ form.foto }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_estilo" class="form-label">Categoria</label>
                {{ form.estilo }}
            </div>
        </div>

        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Salvar Alterações</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

sistema/templates/musica/listar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-mus.html' %}
{% endblock %}

{% block title %}Listagem{% endblock %}

{% block list %}
  <div class="div-lista">
    
    <div class="row">
        
      
        {% for m in musicas %}   
        <div class="card" style="width: 18rem; margin: 10px;">
          {% if m.foto %}
            <img class="card-img-top" src="{{ m.foto.url }}" alt="{{ m.musica }}">
          {% else %}
            <p>Sem foto disponível</p>
          {% endif %}

          
          <div class="card-body">
            <h5 class="card-title">{{ m.banda }} - {{m.musica}}</h5>
            <p class="card-text">Ano de lançamento: {{ m.ano }}</p>
            <p class="card-text">Categoria: {{ m.get_estilo_display }}</p>
        
            <a href="/musica/{{m.id}}" class="btn btn-primary">Editar</a>
            <a href="/musica/deletar/{{m.id}}" class="btn btn-danger">Deletar</a>
          </div>
        </div>
      {% empty %}
        <p>Não há músicas disponíveis no momento.</p>
      {% endfor %}
      
    </div>
  </div>
{% endblock %}

sistema/templates/musica/novo.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-mus.html' %}
{% endblock %}

{% block title %}Adicionar Música{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Adicionar Nova Música</h2>
    <form action="{% url 'add-musicas' %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_banda" class="form-label">Banda</label>
                {{ form.banda }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_musica" class="form-label">Música</label>
                {{ form.musica }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_ano" class="form-label">Ano</label>
                {{ form.ano }}
            </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_foto" class="form-label">Foto</label>
                {{ form.foto }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_estilo" class="form-label">Categoria</label>
                {{ form.estilo }}
            </div>
        </div>


        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Adicionar Música</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}