sistema/colecao/urls.py
from django.urls import path
from colecao.views import ListarColecoes, EditarColecoes, DeletarColecoes, CriarColecoes, FotoColecao, RemoverMusicaColecao, ListarMusicas, AdicionarMusicaColecao


urlpatterns = [
    path('', ListarColecoes.as_view(), name='listar-colecoes'),
    path('<int:pk>/', EditarColecoes.as_view(), name='editar-colecoes'),
    path('deletar/<int:pk>/', DeletarColecoes.as_view(), name='deletar-colecoes'),
    path('novo/', CriarColecoes.as_view(), name='criar-colecoes'),
    path('fotos/<str:arquivo>/', FotoColecao.as_view(), name='foto-colecao'),
    path('<int:colecao_pk>/remover-musica/<int:musica_pk>/', RemoverMusicaColecao.as_view(), name='remover-musica-colecao'),
    path('<int:colecao_pk>/musicas/', ListarMusicas.as_view(), name='listar-musicas-colecao'),
    path('<int:colecao_pk>/adicionar-musica/<int:musica_pk>/', AdicionarMusicaColecao.as_view(), name='adicionar-musica-colecao'),
]

sistema/musica/urls.py
from django.urls import path
from musica.views import ListarMusicas, FotoMusica, AdicionarMusicas, DeletarMusicas, EditarMusicas
from musica.views import APIListarMusicas, APIDeletarMusicas, APIAdicionarMusica, APIEditarMusica
urlpatterns = [
    path('', ListarMusicas.as_view(), name='listar-musicas'),
    path('fotos/<str:arquivo>/', FotoMusica.as_view(), name='foto-musica'),
    path('novo/', AdicionarMusicas.as_view(), name='add-musicas'),
    path('deletar/<int:pk>/', DeletarMusicas.as_view(), name='deletar-musicas'),
    path('<int:pk>/', EditarMusicas.as_view(), name='editar-musicas'),
    path('api/', APIListarMusicas.as_view(), name='api-listar-musicas'),
    path('api/<int:pk>/', APIDeletarMusicas.as_view(), name='api-deletar-musicas'),
    path('api/adicionar/', APIAdicionarMusica.as_view(), name='api-adicionar-musica'),
    path('api/editar/<int:pk>/', APIEditarMusica.as_view(), name='api-editar-musica'),
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from sistema.views import Login, Logout, LoginAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('musica/', include('musica.urls'), name='musica'),
    path('colecao/', include('colecao.urls'), name='colecao'),
    path('autenticacao-api/', LoginAPI.as_view()),
]

sistema/colecao/models.py
from django.db import models
from musica.models import Musica
from django.contrib.auth.models import User

# Create your models here.
class Colecao(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=200)
    foto = models.ImageField(blank=True, null=True, upload_to='colecao/fotos')
    
    musicas = models.ManyToManyField(Musica, related_name='colecoes')
    usuario = models.ForeignKey(User, related_name='colecoes_realizadas', on_delete=models.CASCADE)

    def __str__(self):
        return '{0} - {1}'.format(
            self.nome,
            self.usuario
        )

sistema/colecao/forms.py
from django.forms import ModelForm
from colecao.models import Colecao


class FormularioColecao(ModelForm):

    class Meta:
        model = Colecao
        exclude = ['usuario']

sistema/colecao/views.py
from django.shortcuts import render, redirect, get_object_or_404
from colecao.models import Colecao
from musica.models import Musica
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, View
from django.urls import reverse_lazy
from colecao.forms import FormularioColecao
from django.http import FileResponse, Http404
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
class ListarColecoes(LoginRequiredMixin, ListView):
    """
    View para listar colecoes cadastrados.
    """
    
    model = Colecao
    context_object_name = 'colecoes'
    template_name = 'colecao/listar.html'

    def get_queryset(self):
        # Retorna apenas coleções do usuário atual
        return Colecao.objects.filter(usuario=self.request.user)    


class CriarColecoes(LoginRequiredMixin, CreateView):
    model = Colecao
    form_class = FormularioColecao
    template_name = 'colecao/novo.html'
    success_url = reverse_lazy('listar-colecoes')

    def form_valid(self, form):
        form.instance.usuario = self.request.user 
        return super().form_valid(form)    


class EditarColecoes(LoginRequiredMixin, UpdateView):
    model = Colecao
    form_class = FormularioColecao
    template_name = 'colecao/editar.html'
    success_url = reverse_lazy('listar-colecoes')

    def dispatch(self, request, *args, **kwargs):
        colecao = self.get_object()
        if colecao.usuario != request.user:
            messages.error(request, "Você não tem permissão para editar esta coleção.")
            return redirect('listar-colecoes')
        return super().dispatch(request, *args, **kwargs)    


class DeletarColecoes(LoginRequiredMixin, DeleteView):
    model = Colecao
    template_name = 'colecao/deletar.html'
    success_url = reverse_lazy('listar-colecoes')

    def dispatch(self, request, *args, **kwargs):
        colecao = self.get_object()
        if colecao.usuario != request.user:
            messages.error(request, "Você não tem permissão para editar esta coleção.")
            return redirect('listar-colecoes')
        return super().dispatch(request, *args, **kwargs)    


class FotoColecao(LoginRequiredMixin, View):
    def get(self, request, arquivo):
        try:
            colecao = Colecao.objects.get(foto='colecao/fotos/{}'.format(arquivo))
            return FileResponse(colecao.foto)
        except ObjectDoesNotExist:
            raise Http404("Foto não encontrada ou acesso não autorizado")
        except Exception as exception:
            raise exception
        

class RemoverMusicaColecao(LoginRequiredMixin, View):
    """
    Remove uma música de uma coleção específica.
    """
    def post(self, request, colecao_pk, musica_pk):
        colecao = get_object_or_404(Colecao, pk=colecao_pk, usuario=request.user)
        musica = get_object_or_404(Musica, pk=musica_pk)

        if musica in colecao.musicas.all():
            colecao.musicas.remove(musica)
            messages.success(request, "Música removida com sucesso!")
        else:
            messages.error(request, "Música não encontrada na coleção.")

        return redirect('editar-colecoes', pk=colecao_pk)
    

class ListarMusicas(LoginRequiredMixin, View):
    def get(self, request, colecao_pk):
        colecao = get_object_or_404(Colecao, pk=colecao_pk)
        if colecao.usuario != request.user:
            messages.error(request, "Você não tem permissão para acessar esta página.")
            return redirect('listar-colecoes')
                
        musicas = Musica.objects.exclude(colecoes=colecao) 
        return render(request, 'colecao/listar_musicas.html', {'musicas': musicas, 'colecao': colecao})


class AdicionarMusicaColecao(LoginRequiredMixin, View):
    def post(self, request, colecao_pk, musica_pk):
        colecao = get_object_or_404(Colecao, pk=colecao_pk)

        if colecao.usuario != request.user:
            messages.error(request, "Você não tem permissão para adicionar músicas a esta coleção.")
            return redirect('listar-colecoes')        
                
        musica = get_object_or_404(Musica, pk=musica_pk)
        colecao.musicas.add(musica)
        messages.success(request, f'A música "{musica.musica}" foi adicionada à coleção.')
        return redirect('editar-colecoes', pk=colecao_pk)

sistema/templates/colecao/deletar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-col.html' %}
{% endblock %}

{% block title %}Deletar Coleção{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Deletar Coleção</h2>
    <form action="{% url 'deletar-colecoes' colecao.pk%}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        <center>
            <div class="alert alert-danger" role="alert">
                <p>Tem certeza que deseja excluir a coleção: "{{object.nome}}"?</p>
            </div>

            <input type="submit" value="Confirmar" class="btn btn-primary" />
            <a href="{% url 'listar-colecoes' %}" class="btn btn-danger">Cancelar</a>
        </center>
        
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

sistema/templates/colecao/editar.html
{% extends '../base.html' %}

{% block navbar %}
    {% include 'components/navbar-col.html' %}
{% endblock %}

{% block title %}Listagem{% endblock %}


{% block list %}
  <div class="div-lista" style="padding: 15px;">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>

    <script>
      // Remover mensagens
      setTimeout(function() {
          document.querySelectorAll('.messages .alert').forEach(function(alert) {
              alert.style.transition = "opacity 0.5s ease";
              alert.style.opacity = "0";
              setTimeout(() => alert.remove(), 500); // Remover do DOM após a transição
          });
      }, 2000);
  </script>
    {% endif %}          

    <h3>Coleção:</h3>

        <form action="{% url 'editar-colecoes' object.pk%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row border" style="border-radius: 8px; padding: 10px;">
                <div class="col-md-3">
                    {% if colecao.foto %}
                        <img class="card-img-top" src="{{ colecao.foto.url }}" alt="{{ colecao.nome }}">
                    {% else %}
                        <img class="card-img-top" src="{{ colecao.musicas.all.0.foto.url }}" alt="{{ colecao.nome }}">
                    {% endif %}
                </div>
            
                <div class="col-md-9">
                    <h1>{{ form.nome }}</h1>
                    <br>
                    <div class="mb-3">
                        <label for="descricao" class="form-label">Descrição</label>
                        <textarea class="form-control" id="descricao" name="descricao" rows="3" style="height: 270px;">{{ form.descricao.value }}</textarea>
                    </div>
                    Foto: {{form.foto}}    
                    {{ form.usuario.as_hidden }}
                    {{ form.musicas.as_hidden }}
                    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                </div>
            </div>
            
        </form>
        
        
        
        <h3>Músicas:</h3>
        <div class="row">
      <div class="card" style="width: 18rem; margin: 10px; display: flex; justify-content: center; align-items: center; cursor: pointer;">
        <div style="font-size: 4rem; color: #007bff; text-align: center;" onclick="window.location.href='musicas/' ">
          +
        </div>
      </div>

        {% for m in colecao.musicas.all %}
        <div class="card" style="width: 18rem; margin: 10px;">
          {% if m.foto %}
            <img class="card-img-top" src="{{ m.foto.url }}" alt="{{ m.musica }}">
          {% else %}
          <p>Sem foto disponível</p>
          {% endif %}
          
          <div class="card-body">
            <h5 class="card-title">{{ m.banda }} - {{ m.musica }}</h5>
            <p class="card-text">Ano de lançamento: {{ m.ano }}</p>
            <p class="card-text">Categoria: {{ m.get_estilo_display }}</p>

            <a href="#" class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('remover-musica-{{ m.id }}').submit();">Remover</a>
            <form id="remover-musica-{{ m.id }}" action="{% url 'remover-musica-colecao' colecao.pk m.id %}" method="post" style="display: none;">
              {% csrf_token %}
            </form>


  
          </div> 
        </div>
      {% empty %}
      <div class="card" style="width: 18rem; margin: 10px;">
        <p>Não há músicas nesta coleção.</p>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

sistema/templates/colecao/listar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-col.html' %}
{% endblock %}

{% block title %}Listagem{% endblock %}


{% block list %}
  <div class="div-lista" style="padding: 15px;">

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>

    <script>
      // Remover mensagens
      setTimeout(function() {
          document.querySelectorAll('.messages .alert').forEach(function(alert) {
              alert.style.transition = "opacity 0.5s ease";
              alert.style.opacity = "0";
              setTimeout(() => alert.remove(), 500); // Remover do DOM
          });
      }, 2000); 
  </script>
    {% endif %}       


    <div class="row">
        <h3>Listando {{colecoes|length}} coleções:</h3>
      {% for c in colecoes %}  
      
        <div class="card" style="width: 18rem; margin: 10px;">
          
          {% if c.foto %}
          <img class="card-img-top" src="{{ c.foto.url }}" alt="{{ c.nome }}" style="width: 262px; height: 262px; object-fit: cover;">
          {% else %}
          <img class="card-img-top" src="{{ c.musicas.all.0.foto.url }}" alt="{{ c.nome }}" style="width: 262px; height: 262px; object-fit: cover;">
          {% endif %}
          
          
          <div class="card-body">
            <h5>{{ c.nome }}</h5>
            <p class="card-text">{{  c.descricao }}</p>
            
            <a href="/colecao/{{c.id}}" class="btn btn-primary">Editar</a>
            <a href="/colecao/deletar/{{c.id}}" class="btn btn-danger">Deletar</a>
           
          </div> 
        </div>
      {% empty %}
        <p>Não há coleções disponíveis no momento.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

<!--{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}
-->

sistema/templates/colecao/listar_musicas.html
{% extends '../base.html' %}
{% block navbar %}
    {% include 'components/navbar-col.html' %}
{% endblock %}

{% block title %}Adicionar Músicas{% endblock %}

{% block list %}

<div class="container">
    <h2>Adicionar Músicas à Coleção "{{ colecao.nome }}"</h2>
    <div class="row">
        {% for musica in musicas %}
        <div class="card" style="width: 18rem; margin: 10px;">
            {% if musica.foto %}
            <img src="{{ musica.foto.url }}" class="card-img-top" alt="{{ musica.musica }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ musica.banda }} - {{musica.musica}}</h5>
                <p class="card-text">Ano de lançamento: {{ musica.ano }}</p>
                <p class="card-text">Categoria: {{ musica.get_estilo_display }}</p>
                <form action="{% url 'adicionar-musica-colecao' colecao.pk musica.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </form>
            </div>
        </div>
        {% empty %}
        <p>Não há músicas disponíveis para adicionar.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

sistema/templates/colecao/novo.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar-col.html' %}
{% endblock %}

{% block title %}Criar Coleção{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Criar Nova Coleção</h2>
    <form action="{% url 'criar-colecoes' %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="col-md-6">
            <div class="col-md-6 mb-3">
                <label for="id_nome" class="form-label">Foto</label>
                {{ form.foto }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_nome" class="form-label">Nome da Coleção</label>
                {{ form.nome }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_descricao" class="form-label">Descrição</label>
                {{ form.descricao }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_usuario" class="form-label">Usuário</label>
                <input type="text" class="form-control" value="{{ user.username }}" disabled />
            </div>
            
            <div class="col-md-6 mb-3">
                <label for="id_musicas" class="form-label">Músicas</label>
                {{ form.musicas }}
            </div>
            <br>
            
            <div class="row">
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary me-2">Criar Coleção</button>
                    <a href="{% url 'listar-colecoes' %}" class="btn btn-danger">Cancelar</a>
                </div>
            </div>
            
        </div>


       
    </form>
</div>
{% endblock %}